# -*- coding: utf-8 -*-
"""ML_AAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YwunRWPWdXgvOP3ePk2I-IjpMvVV6Qh
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import mean_squared_error, accuracy_score

df = pd.read_csv("city_day.csv")
df.head()

# Dataset Info
df.info()
df.describe()
df.isnull().sum()

# Data Cleaning
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df = df.dropna(subset=['Date'])
df = df.dropna(subset=['AQI'])

df = df.drop(columns=['Xylene'])

num_cols = df.select_dtypes(include=np.number).columns
imputer = SimpleImputer(strategy='median')
df[num_cols] = imputer.fit_transform(df[num_cols])

# Extract time features
# Save original city for later evaluation
df['City_Original'] = df['City']

# Time features
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day

# Encode city
df = pd.get_dummies(df, columns=['City'], drop_first=True)

df.head()

X = df.drop(columns=['AQI', 'AQI_Bucket', 'Date', 'City_Original'])
y = df['AQI']

# Keep city separately
city_series = df['City_Original']

X_train, X_test, y_train, y_test, city_train, city_test = train_test_split(
    X, y, city_series, test_size=0.2, random_state=42
)

# Feature Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

predictions = model.predict(X_test)

results = pd.DataFrame({
    "City": city_test.values,
    "Actual AQI": y_test.values,
    "Predicted AQI": predictions
})

print(results.head(10))

rmse = np.sqrt(mean_squared_error(y_test, predictions))
print("Overall RMSE:", rmse)

city_rmse = {}

for city in results['City'].unique():
    city_data = results[results['City'] == city]

    if len(city_data) > 10:  # avoid very small samples
        rmse_city = np.sqrt(mean_squared_error(
            city_data['Actual AQI'],
            city_data['Predicted AQI']
        ))
        city_rmse[city] = rmse_city

city_rmse_df = pd.DataFrame(list(city_rmse.items()), columns=['City', 'RMSE'])
city_rmse_df = city_rmse_df.sort_values(by='RMSE')

print(city_rmse_df)

df_cls = df.copy()

df_cls['AQI_Bucket'] = df_cls['AQI_Bucket'].astype('category')

mapping = dict(enumerate(df_cls['AQI_Bucket'].cat.categories))

df_cls['AQI_Bucket'] = df_cls['AQI_Bucket'].cat.codes

X_cls = df_cls.drop(columns=['AQI_Bucket', 'AQI', 'Date', 'City_Original'])
y_cls = df_cls['AQI_Bucket']

city_cls = df_cls['City_Original']

X_train_cls, X_test_cls, y_train_cls, y_test_cls, city_train_cls, city_test_cls = train_test_split(
    X_cls, y_cls, city_cls, test_size=0.2, random_state=42
)

scaler_cls = StandardScaler()

X_train_cls = scaler_cls.fit_transform(X_train_cls)
X_test_cls = scaler_cls.transform(X_test_cls)

clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_cls, y_train_cls)

category_preds = clf.predict(X_test_cls)

results_cls = pd.DataFrame({
    "City": city_test_cls.values,
    "Actual": y_test_cls.values,
    "Predicted": category_preds
})

# Map labels
results_cls['Actual Label'] = results_cls['Actual'].map(mapping)
results_cls['Predicted Label'] = results_cls['Predicted'].map(mapping)

print(results_cls.head(10))

accuracy = accuracy_score(y_test_cls, category_preds)
print("Overall Accuracy:", accuracy)

city_acc = {}

for city in results_cls['City'].unique():
    city_data = results_cls[results_cls['City'] == city]

    if len(city_data) > 10:
        acc = accuracy_score(city_data['Actual'], city_data['Predicted'])
        city_acc[city] = acc

city_acc_df = pd.DataFrame(list(city_acc.items()), columns=['City', 'Accuracy'])
city_acc_df = city_acc_df.sort_values(by='Accuracy', ascending=False)

print(city_acc_df)